name: Run email script

on:
  schedule:
    - cron: '0 9 24 * *'    
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install python-dotenv

    - name: Run Python script
      env:
        # Dessa hämtas från GitHub Settings -> Secrets
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }} 
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python send_email.py
